#!/bin/sh

echo "---Ambilight WiFi prerm ---"

# search for users in system, returns first entry
FOUND_USR=`who | grep -o -m1 '^\w*\b'` || "root"

# stop running daemon before we delete it
HYPERION_RUNNING=false
pgrep ambilightwifid > /dev/null 2>&1 && HYPERION_RUNNING=true

if grep -m1 systemd /proc/1/comm > /dev/null
then
	echo "---> stop init deamon: systemd"
	# systemd
	$HYPERION_RUNNING && systemctl stop ambilightwifid"@${FOUND_USR}" 2> /dev/null
	# disable user specific symlink
	echo "---> Disable service and remove entry"
	systemctl -q disable ambilightwifid"@${FOUND_USR}"
	rm -v /etc/systemd/system/ambilightwifid@.service 2>/dev/null

elif [ -e /sbin/initctl ]
then
	echo "---> stop init deamon: upstart"
	# upstart
	$HYPERION_RUNNING && initctl stop ambilightwifid
	echo "---> Remove upstart service"
	rm -v /etc/init/ambilightwifi* 2>/dev/null
	initctl reload-configuration

else
	echo "---> stop init deamon: sysV"
	# sysV
	$HYPERION_RUNNING && service ambilightwifid stop 2>/dev/null
	echo "---> Remove sysV service"
	update-rc.d -f ambilightwifi remove
	rm /etc/init.d/ambilightwifi* 2>/dev/null
fi

# In case we don't use a service kill all instances
killall ambilightwifid 2> /dev/null

# delete desktop icons; desktop-file-edit is a workaround to hide the entry and delete it afterwards manual.
# TODO Better way for deletion and keep the desktop in sync without logout/login or desktop dependend cmds?
echo "---> Delete Ambilight WiFi desktop icons"
desktop-file-edit --set-key=NoDisplay --set-value=true /usr/share/applications/ambilightwifid.desktop 2>/dev/null
rm -v /usr/share/applications/ambilightwifi* 2>/dev/null
rm -rv /usr/share/pixmaps/ambilightwifi 2>/dev/null

exit 0
